image: ghcr.io/siemens/kas/kas

stages:
  - build

variables:
  DL_DIR: /cache/yocto/downloads
  SSTATE_DIR: /cache/yocto/nosem/sstate
  KAS_WORK_DIR: $CI_PROJECT_DIR/work

.build:
  interruptible: true
  stage: build
  script:
    - echo DL_DIR = $DL_DIR
    - echo SSTATE_DIR = $SSTATE_DIR
    - export ARTIFACT_DIR=$CI_PROJECT_DIR/$KAS_MACHINE
    - rm -rf $KAS_WORK_DIR $ARTIFACT_DIR
    - mkdir --verbose --parents $KAS_WORK_DIR $SSTATE_DIR $DL_DIR $ARTIFACT_DIR
    - kas build kas/nosem.yml
    - cp -L $KAS_WORK_DIR/build/tmp/deploy/images/$KAS_MACHINE/$KAS_TARGET-$KAS_MACHINE.wic.{bz2,bmap} $ARTIFACT_DIR/

build:
  extends: .build
  only:
    - hardknott
    - dunfell
    - tags
  parallel:
    matrix:
      - KAS_MACHINE:
          - aml-s905x-cc
          - aml-s805x-ac
          - amlogic-p241
          - amlogic-s400
          - amlogic-u200
          - khadas-vim3
        KAS_TARGET: core-image-base
  artifacts:
    name: "$KAS_MACHINE-$CI_COMMIT_REF_SLUG"
    expire_in: 1 day
    paths:
      - $CI_PROJECT_DIR/$KAS_MACHINE/

smoke:
  extends: .build
  except:
    - hardknott
    - dunfell
    - tags
  parallel:
    matrix:
      - KAS_MACHINE: aml-s905x-cc
        KAS_TARGET: core-image-minimal
