# Shamelessly inspired from
# https://git.yoctoproject.org/cgit/cgit.cgi/meta-arm/tree/.gitlab-ci.yml

image: ghcr.io/siemens/kas/kas

stages:
  - prep
  - bootstrap
  - build

variables:
  DL_DIR: /cache/yocto/downloads
  SSTATE_DIR: /cache/yocto/nosem/sstate

.setup:
  before_script:
    - echo DL_DIR = $DL_DIR
    - echo SSTATE_DIR = $SSTATE_DIR
    - export KAS_WORK_DIR=$CI_PROJECT_DIR/work/$CI_JOB_NAME
    - export ARTIFACT_DIR=$CI_PROJECT_DIR/$CI_JOB_NAME
    - rm -rf $KAS_WORK_DIR $ARTIFACT_DIR
    - mkdir --verbose --parents $KAS_WORK_DIR $SSTATE_DIR $DL_DIR $ARTIFACT_DIR

.base-build:
  extends: .setup
  interruptible: true
  script:
    - kas build kas/$TARGET_MACHINE.yml:kas/rm-work.yml --target core-image-minimal
    - cp -L $KAS_WORK_DIR/build/tmp/deploy/images/$TARGET_MACHINE/core-image-minimal-$TARGET_MACHINE.wic.{bz2,bmap} $ARTIFACT_DIR/

.actual-build:
  variables:
    TARGET_MACHINE: $CI_JOB_NAME
  extends: .base-build
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - $CI_PROJECT_DIR/$CI_JOB_NAME/

# Build this platform first so the others just reuse most of its state cache
bootstrap:
  variables:
    TARGET_MACHINE: aml-s905x-cc
  extends: .base-build
  stage: bootstrap

aml-s905x-cc:
  extends: .actual-build

aml-s805x-ac:
  extends: .actual-build

amlogic-p241:
  extends: .actual-build

amlogic-s400:
  extends: .actual-build

khadas-vim3:
  extends: .actual-build

#
# Utility tasks, not executed automatically
#

delete-dl-dir:
  extends: .setup
  stage: prep
  when: manual
  script:
  - rm -rf $DL_DIR/*

# Delete all sstate
delete-sstate:
  extends: .setup
  stage: prep
  when: manual
  script:
  - rm -rf $SSTATE_DIR/*
