image: ghcr.io/siemens/kas/kas

stages:
  - build

variables:
  DL_DIR: /cache/yocto/downloads
  SSTATE_DIR: /cache/yocto/nosem/sstate
  KAS_WORK_DIR: $CI_PROJECT_DIR/work

.build:
  interruptible: true
  stage: build
  script:
    - echo DL_DIR = $DL_DIR
    - echo SSTATE_DIR = $SSTATE_DIR
    - rm -rf $KAS_WORK_DIR
    - mkdir --verbose --parents $KAS_WORK_DIR $SSTATE_DIR
    - kas build $KAS_YAML_CFG

build:
  extends: .build
  only:
    - hardknott
    - dunfell
    - tags
  parallel:
    matrix:
      - KAS_MACHINE:
          - aml-s905x-cc
          - aml-s805x-ac
          - amlogic-p241
          - amlogic-s400
          - amlogic-u200
          - khadas-vim3
        KAS_TARGET: core-image-base
        KAS_YAML_CFG:
          - kas/poky.yml
          - kas/oe-core.yml
  before_script:
    - rm -rf $CI_PROJECT_DIR/$KAS_MACHINE
    - mkdir --verbose --parents $CI_PROJECT_DIR/$KAS_MACHINE
  after_script:
    - cp -L $KAS_WORK_DIR/build/tmp/deploy/images/$KAS_MACHINE/$KAS_TARGET-$KAS_MACHINE.wic.{bz2,bmap} $CI_PROJECT_DIR/$KAS_MACHINE/
  artifacts:
    name: "$KAS_MACHINE-$CI_COMMIT_REF_SLUG"
    expire_in: 1 day
    paths:
      - $CI_PROJECT_DIR/$KAS_MACHINE/

linux-nosem-stable:
  extends: .build
  only:
    - hardknott
    - dunfell
    - tags
  parallel:
    matrix:
      - KAS_MACHINE:
          - aml-s905x-cc
          - aml-s805x-ac
          - amlogic-p241
          - amlogic-s400
          - amlogic-u200
        KAS_TARGET: linux-nosem-stable
        KAS_YAML_CFG: kas/poky.yml:kas/frag/linux-nosem-stable.yml

smoke:
  extends: .build
  except:
    - hardknott
    - dunfell
    - tags
  parallel:
    matrix:
      - KAS_MACHINE: aml-s905x-cc
        KAS_TARGET: core-image-minimal
        KAS_YAML_CFG:
          - kas/poky.yml
          - kas/oe-core.yml
      - KAS_MACHINE: aml-s905x-cc
        KAS_TARGET: linux-nosem-stable
        KAS_YAML_CFG: kas/poky.yml:kas/frag/linux-nosem-stable.yml
