#@TYPE: Machine
#@NAME: odroid-c4 machine
#@DESCRIPTION: Reference machine configuration for Hardkernel ODROID-C4 machine

PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
PREFERRED_PROVIDER_virtual/dtb ?= "devicetree-overlays-beelink-gt1-ultimate"
KERNEL_DEVICETREE ?= "amlogic/meson-gxm-gt1-ultimate.dtb"
UBOOT_MACHINE ?= "beelink-gt1-ultimate_defconfig"
MACHINE_FEATURES:append = " alsa bluetooth screen usbgadget usbhost vfat wifi"

# TODO: make this customizable using the boot dev override
# Boot dev options are:
#  - SDcard
#  - eMMC
AMLOGIC_BOOT_DEV ?= "emmc"

require conf/machine/include/amlogic-gxl.inc

# Use wic on this machine
require conf/machine/include/amlogic-wic.inc
