#@TYPE: Machine
#@NAME: khadas-vim3 machine
#@DESCRIPTION: Reference machine configuration for khadas VIM3 machine

PREFERRED_PROVIDER:virtual/kernel ?= "linux-yocto"
KERNEL_DEVICETREE ?= "amlogic/meson-g12b-a311d-khadas-vim3.dtb"
UBOOT_MACHINE ?= "khadas-vim3_defconfig"
MACHINE_FEATURES:append = " alsa bluetooth screen usbgadget usbhost vfat wifi"

# TODO: make this customizable using the boot dev override
# Boot dev options are:
#  - SDcard
#  - eMMC
NOSEM_BOOT_DEV ?= "emmc"

require conf/machine/include/amlogic-a311d.inc

# Use wic on this machine
require conf/machine/include/nosem-wic.inc
