# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "nosem"
BBFILE_PATTERN_nosem = "^${LAYERDIR}/"
BBFILE_PRIORITY_nosem = "7"

LAYERDEPENDS_nosem = "core"
LAYERSERIES_COMPAT_nosem = "mickledore"
