# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-nosem"
BBFILE_PATTERN_meta-nosem = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-nosem = "5"

LAYERDEPENDS_meta-nosem = "core"
LAYERSERIES_COMPAT_meta-nosem = "dunfell"
