header:
  version: 12
  includes:
  - kas/include/deps.yml
  - kas/include/base.yml

repos:
  core:
    url: https://git.openembedded.org/openembedded-core
    path: layers/oe-core
    refspec: langdale
    layers:
      meta:
  bitbake:
    url: https://git.openembedded.org/bitbake
    path: layers/bitbake
    refspec: '2.2'
    layers:
      conf: disabled

distro: nodistro
