header:
  version: 17
  includes:
  - kas/include/deps.yml
  - kas/include/base.yml

repos:
  poky:
    url: https://git.yoctoproject.org/poky
    path: layers/poky
    branch: scarthgap
    layers:
      meta:
      meta-poky:

distro: poky
